name: utslogin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  firebase_core: 1.10.5
  firebase_auth: 3.3.3
  pinput: 1.2.2
  cloud_firestore: 3.1.4
  firebase_storage: 10.2.3
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

